apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-app
  namespace: argocd
spec:
  project: default
  source:
    helm:
      parameters:
      - name: readinessProbe.httpGet.path
        value: /
      valueFiles:
      - values.yaml
    path: helm/metrics-helm
    repoURL: git@github.com:dev4901/metrics-sre-assignment.git
    targetRevision: master
  destination:
    namespace: metrics-argotest
    server: https://test2-control-plane:6443
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
