apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-job-pre-install"
#  generateName: helm-dependency-update
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: helm-dependency-update
          image: "helm/helm:latest"
          command: ["helm", "dependency", "build"]
      restartPolicy: OnFailure
#  backoffLimit: 4
#  completions: 1
#  parallelism: 1
